#
# This file is part of Brazil Data Cube Reproducible Research Management Server.
# Copyright (C) 2021 INPE.
#
# Brazil Data Cube Reproducible Research Management Server is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

[pytest]
addopts = --strict --color=auto --cov=bdcrrm_server --cov-report=term-missing -v --cov-report=xml:coverage.xml
testpaths = tests
